### ISSUE TITLE
Check if Database is in UTF8

### ISSUE THREAD

**Issue by drkmtrx** [Algo-Web/POData-Laravel#208] opened 2020-02-17 16:55 UTC
In [primitiveToString()](https://github.com/Algo-Web/POData-Laravel/blob/master/src/Serialisers/SerialiseLowLevelWritersTrait.php#L177) please check if the content is already in utf8 before calling utf8_encode().
When using Postgres data is already in utf8 and this utf8_encode break special characters like umlaut.

**Comment by c-harris** [comment] 2020-02-18 08:28
just sorting out a few things with the test setup (you got your own app setup in regression tests) but we can get on this in the near future. 

I am thinking about using mb_detect_encoding instead of checking the database, thoughts?

**Comment by CyberiaResurrection** [comment] 2020-02-19 05:40
@bgoak , since @c-harris and I have re-arranged the IronicSerialiser somewhat since your initial report, could you supply a string that's being mangled (such as one with an umlaut)?

From your report, that should be passed through unchanged - if not, could you also supply what it should be processed into?

**Comment by drkmtrx** [comment] 2020-02-19 08:28
For example a typical german name like Müller, this should be passed unchanged.
So when mb_detect_encoding detects a string in utf8 (or ascii) it should just skip the encode.

**Comment by CyberiaResurrection** [comment] 2020-02-19 08:48
Sweet, thanks for that.  Now to pry some of these hands off my time.

**Comment by CyberiaResurrection** [comment] 2020-02-20 13:46
@bgoak , can you try #212 and see if it solves your reported problem?

**Comment by CyberiaResurrection** [comment] 2020-02-22 11:10
This issue is simple and well-characterised, so I'm closing it as fixed.

**Closed as completed by CyberiaResurrection** 2020-02-22 11:10 UTC
