### ISSUE TITLE
how to configure this in laravel ?

### ISSUE THREAD

**Issue by dsv4890** [Algo-Web/POData-Laravel#170] opened 2018-07-12 08:50 UTC
what will be next step after adding trait in model ?

**Comment by donmbelembe** [comment] 2018-07-12 09:03
go to 
http://localhost:8000/odata.svc
http://localhost:8000/odata.svc/$metadata
http://localhost:8000/odata.svc/ModelName

please let me know if it works for you because i'm getting this error
_A non well formed numeric value encountered_

**Comment by dsv4890** [comment] 2018-07-12 09:29
Do i have to declare this path in my web.php file right? how can i use all
that function like $count, $top ect..
Best Regards,
Dhruvisha Vasavada

**Comment by dsv4890** [comment] 2018-07-12 09:30
Do i have to declare this path in my web.php file right? how can i use all
that function like $count, $top ect..

**Comment by c-harris** [comment] 2018-07-12 09:31
Have you exposed the model with the trait? 

The routes are defined by the route service provider.

@donmbelembe where are you encountering that error

**Comment by dsv4890** [comment] 2018-07-12 09:32
http://localhost:8000/odata.svc/$metadata this URL is working for me but when I write ModelName it redirecting  back to a login page

**Comment by donmbelembe** [comment] 2018-07-12 09:43
I'm also new to Odata
 so i don't know, just trying out

**Comment by donmbelembe** [comment] 2018-07-12 09:47
1. this link: http://localhost:8000/odata.svc/$metadata 
produce this error _Class 'Symfony\Component\Yaml\Yaml' not found_

2. when I write ModelName it redirecting to Home page

3. @c-harris  yeah and when trying to access http://localhost:8000/odata.svc i'm getting _A non well formed numeric value encountered_ on **\vendor\symfony\http-foundation\Response.php**

UPDATE

**Comment by dsv4890** [comment] 2018-07-12 09:52
Do we need to add Class 'Symfony\Component\Yaml\Yaml'  this manually in the composer 
i have checked in composer.json this class is already there still I'm getting the same error  on this link: http://localhost:8000/odata.svc/$metadata

**Comment by donmbelembe** [comment] 2018-07-12 10:08
I've installed `composer require symfony/yaml`
i'm not getting this error anymore _Class 'Symfony\Component\Yaml\Yaml' not found_

but still my model redirecting to /home and 
http://localhost:8000/odata.svc/$metadata & http://localhost:8000/odata.svc gives this error A non well formed numeric value encountered on \vendor\symfony\http-foundation\Response.php

**Comment by dsv4890** [comment] 2018-07-13 07:14
I'm also getting the same error with laravel 5.6

**Comment by CyberiaResurrection** [comment] 2018-07-14 15:53
@donmbelembe , @dsv4890 , can you try again, please?  I've rolled up @NoelDeMartin 's pull request that fixed at least one underlying issue.

**Comment by donmbelembe** [comment] 2018-07-15 04:53
thank you ,
but unfortunately after updating to the last version and set the trait to the User Model, i'm getting the following error

`php artisan package:discover

In MetadataProvider.php line 140:

  Undefined index: User`

**Comment by CyberiaResurrection** [comment] 2018-07-15 05:04
@donmbelembe , thanks for your feedback.  

Blast.  I'm working on a pull request at the moment that might get you out of a jam (#171 ) - if I give you the details, are you able to update with them and see if pain persists?

**Comment by donmbelembe** [comment] 2018-07-15 05:11
of course @CyberiaResurrection

**Comment by CyberiaResurrection** [comment] 2018-07-15 05:14
Here we go - you'll need to tweak your project's composer.json file somewhat:

1 - Add the following section:
`    "repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/CyberiaResurrection/podata-laravel.git",
        "no-api": true
      }
    ],`

2 - Change your podata-laravel dependency line as follows:
`"algo-web/podata-laravel": "dev-CleanUpAsserts as dev-master",`

After that, you'll need to run composer update.  Could you let me know how that goes? 

I'm still arguing with getting the test suite working under Laravel 5.6.

**Comment by donmbelembe** [comment] 2018-07-15 05:39
Thanks dude, I followed your steps, now http://localhost:8000/odata.svc and http://localhost:8000/odata.svc/$metadata are returning good response, however When trying to access my model like this http://localhost:8000/odata.svc/ModelName It's redirecting to home page

**Comment by CyberiaResurrection** [comment] 2018-07-15 05:44
@donmbelembe , thanks heaps for your feedback and confirming a certain wombat (ie, @CyberiaResurrection) had not mucked that particular bit up.

This may be a really dumb question - crack up laughing if you feel the need -  but are you logged into your project before browsing to odata.svc/ModelName ?

**Comment by c-harris** [comment] 2018-07-15 05:48
@CyberiaResurrection should we perhaps consider disabling auth by default as it is not detailed in odata itself?

**Comment by CyberiaResurrection** [comment] 2018-07-15 05:52
I direct my learned colleague's attention to the README.

@donmbelembe , can you try adding the following line to your project's .env file?
`APP_DISABLE_AUTH=true`

**Comment by donmbelembe** [comment] 2018-07-15 07:57
@CyberiaResurrection About your question, When I'm not logged in it is redirecting to the login page and when it's already logged in it is redirecting to /home. actually my home page has auth middleware

**Comment by donmbelembe** [comment] 2018-07-15 08:01
The trait is already set in my model but http://localhost:8000/odata.svc/ModelName is redirecting to /home

**Comment by donmbelembe** [comment] 2018-07-15 08:04
@CyberiaResurrection even with `APP_DISABLE_AUTH=true` i'm getting the same result

**Comment by CyberiaResurrection** [comment] 2018-07-15 08:16
@donmbelembe , that's a new problem.  APP_DISABLE_AUTH should do what it says on the tin - thanks for rumbling a spot where I've outsmarted myself.

**Comment by CyberiaResurrection** [comment] 2018-07-15 08:38
@donmbelembe , I've pushed out what I hope is a fix for APP_DISABLE_AUTH - does it get you out of trouble after running composer update?

**Comment by donmbelembe** [comment] 2018-07-15 10:00
I think It works now.

So http://localhost:8000/odata.svc/User return an xml with 404 status code but http://localhost:8000/odata.svc/Users return data, so this mean we must call call the model in plural ?

_Maybe I should learn more about Odata, I'm testing first_

**Comment by CyberiaResurrection** [comment] 2018-07-15 10:43
@donmbelembe , thanks for your continued feedback and patience.

We followed Laravel convention and thus pluralised the model names to use as endpoints.  That's an implementation choice in POData-Laravel, not anything intrinsic to OData itself.

**Comment by donmbelembe** [comment] 2018-07-15 10:52
Okey. Thanks to you also for your help

**Comment by CyberiaResurrection** [comment] 2018-07-15 10:59
Thanks for your bug reports.  As you've confirmed that your issue is fixed in that branch, I'll close this issue.

**Closed as completed by CyberiaResurrection** 2018-07-15 10:59 UTC

**Comment by CyberiaResurrection** [comment] 2018-07-16 16:18
@donmbelembe , I've rolled those changes up, so you'll need to undo those changes I asked you to make in your project's composer.json file.
